---
 - name: PLaybokt o manage services on Linux Servers
   hosts: workers
   become: yes
   vars:
           - myvar1: cron # Name of Service
           - myvar2: restarted # State of Service

   tasks:
           - name: Service {{myvar1}} is getting {{myvar2}}
             service:
                     name: "{{myvar1}}"
                     state: "{{myvar2}}"

           - name: Printing variables name
             debug:
                     msg: myvar is {{myvar1}}
           
